### PR TITLE
select all groups wip

### PR DESCRIPTION
**Pull request by skumo**
@elisechant , could you pls review ... also, tried getting the checkbox inline and need some help with  that ...

### CODE REVIEW

**Comment by elisechant** [comment]
This looks like a dupe of https://github.com/CodeforAustralia/cese-snippet/pull/165 @skumo

**Comment by skumo** [comment]
@elisechant , managed to get the new component working for selecting all schools ... I think I overthink(ed) it .. anyway ..

**Comment by elisechant** [comment]
Still not working as expected:

screen shot 2018-05-05 at 7 56 20 am

**Comment by skumo** [comment]
This branch is closed. Too many Merge Conflicts. the functionality is replicated in a different branch call sk-selectAllYears-07May

**Pull request closed without merging**
